open Items;

let anduril = {
  id: createItemId(),
  name: {js|Andúril|js},
  description: "A longsword reforged from the shards of Narsil.",
  image:
    ItemImage.make(
      "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword3.png",
    ),
  rarity: Legendary,
  kind: Weapon(TwoHanded(Sword)),
  size: (4, 2),
};

let sting = {
  id: createItemId(),
  name: "Sting",
  description: "A small sword, not much larger than a dagger, that glows when orcs or goblins are nearby.",
  image:
    ItemImage.make(
      "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword4.png",
    ),
  rarity: Epic,
  kind: Weapon(OneHanded(ShortSword)),
  size: (3, 2),
};

let theOneRing = {
  id: createItemId(),
  name: "The One Ring",
  description: {|A small golden ring. When exposed to flame, an inscription in black speech reads: "One ring to rule them all, one ring to find them, one ring to bring them all and in the darkness bind them."|},
  image:
    ItemImage.make(
      "https://web.poecdn.com/image/Art/2DItems/Rings/Ring4.png",
    ),
  rarity: Legendary,
  kind: Apparel(Ring),
  size: (1, 1),
};

let morgulBlade = {
  id: createItemId(),
  name: "Morgul Blade",
  description: "A magical and poisonous dagger.",
  image:
    ItemImage.make(
      "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger8.png",
    ),
  rarity: Rare,
  kind: Weapon(OneHanded(Dagger)),
  size: (3, 1),
};

let urukHaiChestPiece = {
  id: createItemId(),
  name: "Uruk Hai Chestpiece",
  description: "Body armor worn by the Uruk Hai of Isengard.",
  image:
    ItemImage.make(
      "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr1A.png",
    ),
  rarity: Uncommon,
  kind: Apparel(Chestpiece),
  size: (3, 2),
};

let predefinedItems = [
  sting,
  anduril,
  theOneRing,
  morgulBlade,
  urukHaiChestPiece,
];

let backpack: Container.container = {size: (20, 20), items: []};

let preloadImages = [
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Claws/Claw9.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Daggers/Dagger9.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/OneHandAxe9.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandMaces/OneHandMace9.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/OneHandSword9.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandSwords/TheGoddessUnleashed.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Rapiers/Rapier9.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Scepters/scepter9.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Wands/Wand1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Wands/Wand2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Wands/Wand3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Wands/Wand4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Wands/Wand5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Wands/Wand6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/Wands/Wand7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Bows/Bow9.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/FishingRods/FishingRod1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/Staff1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/Staff2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/Staff3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/Staff4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/Staff5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/Staff6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/Staff7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/Staff8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandAxes/TwoHandAxe1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandAxes/TwoHandAxe2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandAxes/TwoHandAxe3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandAxes/TwoHandAxe4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandAxes/TwoHandAxe5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandAxes/TwoHandAxe6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandAxes/TwoHandAxe7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandAxes/TwoHandAxe8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandMaces/TwoHandMace1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandMaces/TwoHandMace2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandMaces/TwoHandMace3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandMaces/TwoHandMace4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandMaces/TwoHandMace5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandMaces/TwoHandMace6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandMaces/TwoHandMace7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandMaces/TwoHandMace8.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword1.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword2.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword3.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword4.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword5.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword6.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword7.png",
  "https://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/TwoHandSwords/TwoHandSword8.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDex1A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDex1B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDex1C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDex2C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDex3A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDex3B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDex3C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDexInt1A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDexInt1B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDexInt1C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDexInt2A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDexInt2B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDexInt2C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyDexInt4C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyInt1A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyInt1B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyInt1C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyInt2A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyInt2B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyInt2C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr1A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr1B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr1C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr2A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr2B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr2C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr3C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr3CUnique.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStr4A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrDex1A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrDex1B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrDex1C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrDex2A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrDex2B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrDex2C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrDexInt1C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrInt1A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrInt1B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrInt1C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrInt2A.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrInt2B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrInt2C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/BodyStrInt3C.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/DemigodsArmour.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/SacrificialGarb.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsDex1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsDex2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsDex3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsDex4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsDexInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsDexInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsDexInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsDexInt4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsInt4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStr1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStr2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStr3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStr4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStrDex1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStrDex2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStrDex3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStrInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStrInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/BootsStrInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/DemigodsStride.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/TwoTonedBoots.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/TwoTonedBoots2B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Boots/TwoTonedBoots3B.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/DemigodsTouch.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/FingerlessSilkGloves.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesDex1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesDex2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesDex3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesDex4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesDexInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesDexInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesDexInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesInt4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStr1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStr2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStr3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStr4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStrDex1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStrDex2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStrDex3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStrInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStrInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GlovesStrInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/GripGlovesBaseType.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Gloves/SpikedGloves.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/BoneHelm.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/Demigodstriumph.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex10.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex5.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex6.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex7.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex8.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDex9.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt10.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt11.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt5.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt6.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt7.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt8.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetDexInt9.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt10.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt11.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt5.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt6.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt7.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt8.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetInt9.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr10.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr11.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr5.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr6.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr7.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr8.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStr9.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex10.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex5.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex6.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex7.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex8.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrDex9.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt1.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt10.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt2.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt3.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt4.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt5.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt6.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt7.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt8.png",
  "https://web.poecdn.com/image/Art/2DItems/Armours/Helmets/HelmetStrInt9.png",
];
